# Generated by Django 5.1.3 on 2024-11-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_alter_orderitem_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
