# Generated by Django 5.1.3 on 2024-12-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_lowstocknotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['timestamp']},
        ),
    ]
